version: 2
jobs:
  build:
    ...
  deploy:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Install Python
          command: |
            pip install go
      - run:
          name: Commit to Shipa
          command: |
            pip install shipa-ci && shipa-ci --app=circle-ci --server=$SHIPASERVER --token=$TOKEN
