version: 2
language: python
python:
  - "2.7"

jobs:
  include:
    - stage: build
      script: 'python -m unittest discover'

    - stage: deploy
      script: 'pip install shipa-ci && shipa-ci --app=circle-ci --server=$SHIPASERVER --token=$TOKEN'
